### AUTENTICAÇÃO (LOGIN COMO ADMIN)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@grifo.com",
  "password": "SenhaForte@123"
}

### CRIAR SUBGÊNERO COM SUCESSO (201 CREATED)
POST http://localhost:8080/api/v1/genres/d49af9ca-4488-4e33-913d-d2c1613ac3b2/subgenres
Content-Type: application/json

{
  "translations": [
    {
      "languageCode": "pt-BR",
      "name": "Alta Fantasia"
    },
    {
      "languageCode": "en-US",
      "name": "High Fantasy"
    }
  ]
}

### ERRO - GÊNERO PAI NÃO ENCONTRADO (404 NOT FOUND)
POST http://localhost:8080/api/v1/genres/d49af9ca-4488-4e43-913d-d2c1613ac3b2/subgenres
Content-Type: application/json

{
  "translations": [
    {
      "languageCode": "pt-BR",
      "name": "Fantasia Sombria"
    }
  ]
}

### ERRO DE CONFLITO - NOME DUPLICADO (409 CONFLICT)
POST http://localhost:8080/api/v1/genres/d49af9ca-4488-4e33-913d-d2c1613ac3b2/subgenres
Content-Type: application/json

{
  "translations": [
    {
      "languageCode": "pt-BR",
      "name": "alta fantasia"
    }
  ]
}

### ERRO DE VALIDAÇÃO DTO (400 BAD REQUEST)
POST http://localhost:8080/api/v1/genres/d49af9ca-4488-4e33-913d-d2c1613ac3b2/subgenres
Content-Type: application/json

{
  "translations": [
    {
      "languageCode": "pt-br",
      "name": ""
    }
  ]
}

### PREPARAÇÃO: LOGIN DO LEITOR (READER)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "barbara@grifo.com",
  "password": "SenhaForte@123"
}

### ERRO DE PERMISSÃO (403 FORBIDDEN)
POST http://localhost:8080/api/v1/genres/d49af9ca-4488-4e33-913d-d2c1613ac3b2/subgenres
Content-Type: application/json

{
  "translations": [
    {
      "languageCode": "pt-BR",
      "name": "Fantasia Urbana"
    }
  ]
}