### Cadastrar Novo Usuário (Sucesso)
POST http://localhost:8080/api/v1/register
Content-Type: application/json
Accept-Language: pt-BR

{
  "name": "Luiza Sonza",
  "email": "luiza@grifo.com",
  "password": "SenhaForte@123"
}

### Cadastrar Usuário Já Cadastrado (Conflito)
POST http://localhost:8080/api/v1/register
Content-Type: application/json
Accept-Language: pt-BR

{
  "name": "Bárbara Nascimento",
  "email": "barbara@grifo.com",
  "password": "SenhaForte@123"
}

### Cadastrar Usuário com Dados Invalidos (Bad Request)
POST http://localhost:8080/api/v1/register
Content-Type: application/json
Accept-Language: pt-BR

{
  "name": "Bárbara Nascimento",
  "email": "barbara",
  "password": "Senhaforte@123"
}