### AUTENTICAÇÃO (LOGIN COMO ADMIN)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@grifo.com",
  "password": "SenhaForte@123"
}

### CADASTRAR AUTOR COM SUCESSO (201 CREATED)
POST http://localhost:8080/api/v1/authors
Content-Type: application/json

{
  "displayName": "J.R.R. Tolkien",
  "sortName": "Tolkien, J.R.R.",
  "birthDate": "1892-01-03",
  "website": "https://www.tolkienestate.com",
  "localizations": [
    {
      "languageCode": "pt-BR",
      "biography": "John Ronald Reuel Tolkien foi um escritor, professor universitário e filólogo britânico, criador de O Senhor dos Anéis."
    },
    {
      "languageCode": "en-US",
      "biography": "John Ronald Reuel Tolkien was an English writer, poet, philologist, and academic, best known as the author of the high fantasy works The Hobbit and The Lord of the Rings."
    }
  ]
}

### ERRO - TENTAR CADASTRAR AUTOR SEM BIOGRAFIA (400 BAD REQUEST)
POST http://localhost:8080/api/v1/authors
Content-Type: application/json

{
  "displayName": "Stephen King",
  "sortName": "King, Stephen",
  "birthDate": "1947-09-21",
  "website": "https://stephenking.com",
  "localizations": []
}

### ERRO - TENTAR CADASTRAR AUTOR FALTANDO DADOS OBRIGATÓRIOS (400 BAD REQUEST)
POST http://localhost:8080/api/v1/authors
Content-Type: application/json

{
  "displayName": "",
  "sortName": "King, Stephen",
  "localizations": [
    {
      "languageCode": "portugues",
      "biography": "O formato de idioma está errado, deveria ser pt-BR."
    }
  ]
}
