CREATE TABLE tb_users (
    id UUID PRIMARY KEY,

    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    nickname VARCHAR(50) NOT NULL UNIQUE,

    password VARCHAR(255),

    google_id VARCHAR(255) UNIQUE,

    role VARCHAR(50) NOT NULL DEFAULT 'READER',

    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);